// DO NOT EDIT. ops/registry/apps.yml에서 생성된 홈페이지 앱 메타데이터다.
export const generatedAppMeta = [
  {
    "id": "outbom",
    "name": "야외봄",
    "englishName": "OutBom",
    "repo": "robom-labs/outbom",
    "version": "0.30.0",
    "dataVersion": "runtime-weather-v1",
    "webUrl": "https://robom-labs.github.io/outbom/",
    "healthcheckUrl": "https://robom-labs.github.io/outbom/",
    "deployProvider": "github-pages",
    "basePath": "/outbom/",
    "privacyUrl": "https://robom.kr/privacy/outbom",
    "supportUrl": "https://robom.kr/support",
    "androidAppId": "kr.robom.outbom",
    "iosBundleId": "kr.robom.outbom",
    "googlePlayUrl": "https://play.google.com/store/apps/details?id=kr.robom.outbom",
    "googlePlayStatus": "live",
    "appStoreUrl": "",
    "appStoreStatus": "planned",
    "pwaInstallUrl": "https://robom-labs.github.io/outbom/",
    "stableInstallUrl": "https://robom.kr/get/outbom",
    "mobileStatus": "native-production-live",
    "familySpecVersion": "1.1.0",
    "lastVerifiedAt": "2026-08-12T00:00:27+09:00",
    "lastDeployedSha": "1445e0f91831c1d813fecd71e297d04f7bb85ae5",
    "lastDataSyncAt": "2026-07-16T13:42:23+09:00",
    "freshnessStatus": "runtime"
  },
  {
    "id": "homebom",
    "name": "청약봄",
    "englishName": "HomeBom",
    "repo": "robom-labs/homebom",
    "version": "0.17.1",
    "dataVersion": "official-notices-runtime-v1",
    "webUrl": "https://robom-labs.github.io/homebom/",
    "healthcheckUrl": "https://robom-labs.github.io/homebom/",
    "deployProvider": "github-pages",
    "basePath": "/homebom/",
    "privacyUrl": "https://robom.kr/privacy/homebom",
    "supportUrl": "https://robom.kr/support",
    "androidAppId": "kr.robom.homebom",
    "iosBundleId": "kr.robom.homebom",
    "googlePlayUrl": "https://play.google.com/store/apps/details?id=kr.robom.homebom",
    "googlePlayStatus": "live",
    "appStoreUrl": "",
    "appStoreStatus": "planned",
    "pwaInstallUrl": "https://robom-labs.github.io/homebom/",
    "stableInstallUrl": "https://robom.kr/get/homebom",
    "mobileStatus": "native-production-live",
    "familySpecVersion": "1.1.0",
    "lastVerifiedAt": "2026-08-23T16:09:40+09:00",
    "lastDeployedSha": "599180c6d51fda5086a23d6845c02c8b8353fc15",
    "lastDataSyncAt": "2026-08-08T21:05:02+09:00",
    "freshnessStatus": "runtime"
  },
  {
    "id": "runningbom",
    "name": "러닝봄",
    "englishName": "RunningBom",
    "repo": "robom-labs/runningbom",
    "version": "0.21.0",
    "dataVersion": "2026.08.22-race-data-52",
    "webUrl": "https://robom-labs.github.io/runningbom/",
    "healthcheckUrl": "https://robom-labs.github.io/runningbom/",
    "deployProvider": "github-pages",
    "basePath": "/runningbom/",
    "privacyUrl": "https://robom.kr/privacy/runningbom",
    "supportUrl": "https://robom.kr/support",
    "androidAppId": "kr.robom.runningbom",
    "iosBundleId": "kr.robom.runningbom",
    "googlePlayUrl": "https://play.google.com/store/apps/details?id=kr.robom.runningbom",
    "googlePlayStatus": "live",
    "appStoreUrl": "",
    "appStoreStatus": "planned",
    "pwaInstallUrl": "https://robom-labs.github.io/runningbom/",
    "stableInstallUrl": "https://robom.kr/get/runningbom",
    "mobileStatus": "native-production-live",
    "familySpecVersion": "1.1.0",
    "lastVerifiedAt": "2026-08-22T15:13:45+09:00",
    "lastDeployedSha": "bfcc686142eca9c9719de5627e84a1e2e13f66ef",
    "lastDataSyncAt": "2026-08-22T03:59:41+09:00",
    "freshnessStatus": "healthy"
  },
  {
    "id": "certbom",
    "name": "자격증봄",
    "englishName": "CertBom",
    "repo": "robom-labs/certbom",
    "version": "0.9.0",
    "dataVersion": "2026.07.24-v4",
    "webUrl": "https://certbom.vercel.app/",
    "healthcheckUrl": "https://certbom.vercel.app/",
    "deployProvider": "vercel",
    "basePath": "/",
    "privacyUrl": "https://robom.kr/privacy/certbom",
    "supportUrl": "https://robom.kr/support",
    "androidAppId": "kr.robom.certbom",
    "iosBundleId": "kr.robom.certbom",
    "googlePlayUrl": "https://play.google.com/store/apps/details?id=kr.robom.certbom",
    "googlePlayStatus": "live",
    "appStoreUrl": "",
    "appStoreStatus": "planned",
    "pwaInstallUrl": "https://certbom.vercel.app/",
    "stableInstallUrl": "https://robom.kr/get/certbom",
    "mobileStatus": "native-production-live",
    "familySpecVersion": "1.1.0",
    "lastVerifiedAt": "2026-08-11T23:57:08+09:00",
    "lastDeployedSha": "8cebe2ba9414717b2162329efcae2565e5aff7fd",
    "lastDataSyncAt": "2026-07-24T14:30:00+09:00",
    "freshnessStatus": "last-known-good"
  }
] as const;
